# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  DeployCreateReactAppToAWS:
    docker:
      - image: alpine:3.7
    parameters:
      s3bucket:
        type: string
        default: ""
      cloudFrontID:
        type: string
        default: ""
      language:
        type: string
        default: "en"
    steps:
      - run:
          name: Step 1
          command: |
            echo "Command 1"
            echo "The S3 URL is: <<parameters.s3bucket>>"
      - run:
          name: Step 2
          command: |
            echo "Command 2"
            echo "S3 bucket URL: <<parameters.s3bucket>>"
            echo "CloufFront distribution ID: <<parameters.cloudFrontID>>"
            echo "Language: <<parameters.language>>"

workflows:
  WorkflowA:
    jobs:
      - welcome/run
  WorkflowB:
    jobs:
      - DeployCreateReactAppToAWS:
          s3bucket: "s3://sampleBucketURL.com"
          cloudFrontID: "ABCD1234"