# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
  workflowA:
    jobs:
      - welcome/run
  workflowB:
    jobs:
      - welcome/run