# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  SimpleJob:
    docker:
      - image: alpine:3.7
    parameters:
      s3bucket:
        type: string
        default: ""
    steps:
      - run:
          name: Step 1
          command: |
            echo "Command 1"
            echo <<parameters.s3bucket>>
      - run:
          name: Step 2
          command: echo "Command 2"

workflows:
  WorkflowA:
    jobs:
      - welcome/run
  WorkflowB:
    jobs:
      - SimpleJob:
          s3bucket: "s3://sampleBucketURL.com"