# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

executors:
  alpine37:
    docker:
      - image: alpine:3.7

commands:
  deploy_create_react_app_to_aws:
    description: "A description for a command"
    parameters:
      s3bucket:
        type: string
        default: ""
      cloudFrontID:
        type: string
        default: ""
      language:
        type: string
        default: "en"
    steps:
      - run:
          name: Step 1
          command: |
            echo "Command 1"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              #circleci step halt
              echo "Deploying to production"
            fi

            echo "Deploying to staging"

      - run:
          name: Step 2
          command: |
            echo "Command 2"
            echo "S3 bucket URL: <<parameters.s3bucket>>"
            echo "CloufFront distribution ID: <<parameters.cloudFrontID>>"
            echo "Language: <<parameters.language>>"

jobs:
  timavera-is:
    executor: alpine37
    steps:
      - deploy_create_react_app_to_aws:
          s3bucket: "s3://timavera.is"
          cloudFrontID: "ABCD1234"
#  timavera-com:
#    executor: alpine37
#    steps:
#      - deploy_create_react_app_to_aws:
#          s3bucket: "s3://timavera.com"
#          cloudFrontID: "ABCD1234"